celmedia_admin_theme_homepage:
    path:     /
    defaults: { _controller: CelmediaAdminThemeBundle:Default:index }



# trabajar con este route

app_admin_theme_mapa:
    path:     /emergencias
<<<<<<< HEAD
    defaults: { _controller: CelmediaAdminThemeBundle:Emergencia:emergencias }
=======
    defaults: { _controller: CelmediaAdminThemeBundle:Emergencias:emergencias }


remote_get_directorios:
    path:     /server/get/directorios
    defaults: { _controller: CelmediaAdminThemeBundle:Servicios:getDirectorios }







>>>>>>> c02398d86cbf5a9b76ac0cea31de8f7df0a6f613

get_emergencias:
    path:      /getEmergencias
    defaults:  { _controller: CelmediaAdminThemeBundle:Emergencia:getEmergencias }
    options:
        expose: true





















celmedia_admin_theme_participantes:
    path:     /manager/participantes
    defaults: { _controller: CelmediaAdminThemeBundle:Default:participantes }

celmedia_admin_theme_codigos:
    path:     /manager/codigos
    defaults: { _controller: CelmediaAdminThemeBundle:Default:codigos }


celmedia_admin_theme_aplicaciones:
    path:     /manager/aplicacion
    defaults: { _controller: CelmediaAdminThemeBundle:Default:aplicaciones }



celmedia_admin_theme_campana:
    path:     /manager/campana
    defaults: { _controller: CelmediaAdminThemeBundle:Default:campanas }



celmedia_admin_theme_enviar:
    path:     /manager/crear/envio
    defaults: { _controller: CelmediaAdminThemeBundle:Default:envios }



celmedia_admin_theme_get_tipo_mensaje_form:
    path:      /manager/tipo_mensaje/{id_tipo}
    defaults:  { _controller: CelmediaAdminThemeBundle:Default:getTipoMensajeForm }
    options:
        expose: true

celmedia_admin_theme_get_tipo_mensaje_image:
    path:      /manager/tipo_mensaje_imagen/{id_tipo}
    defaults:  { _controller: CelmediaAdminThemeBundle:Default:getMensajeImagenForm }
    options:
        expose: true


# security
celmedia_admin_theme_login:
    path:     /login
    defaults: { _controller: CelmediaAdminThemeBundle:Security:login }

login_check:
    path: /login_check

